"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([[301],{

/***/ 27626:
/***/ (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {

// ESM COMPAT FLAG
__webpack_require__.r(__webpack_exports__);

// EXPORTS
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return /* binding */ Layout; }
});

// EXTERNAL MODULE: ./node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/slicedToArray.js
var slicedToArray = __webpack_require__(5574);
var slicedToArray_default = /*#__PURE__*/__webpack_require__.n(slicedToArray);
// EXTERNAL MODULE: ./node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/toConsumableArray.js
var toConsumableArray = __webpack_require__(19632);
var toConsumableArray_default = /*#__PURE__*/__webpack_require__.n(toConsumableArray);
// EXTERNAL MODULE: ./node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/objectSpread2.js
var objectSpread2 = __webpack_require__(97857);
var objectSpread2_default = /*#__PURE__*/__webpack_require__.n(objectSpread2);
// EXTERNAL MODULE: ./node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/createForOfIteratorHelper.js
var createForOfIteratorHelper = __webpack_require__(64599);
var createForOfIteratorHelper_default = /*#__PURE__*/__webpack_require__.n(createForOfIteratorHelper);
// EXTERNAL MODULE: ./src/.umi-production/exports.ts + 35 modules
var _umi_production_exports = __webpack_require__(80854);
// EXTERNAL MODULE: ./node_modules/react/index.js
var react = __webpack_require__(67294);
// EXTERNAL MODULE: ./node_modules/@ant-design/pro-layout/es/ProLayout.js + 75 modules
var ProLayout = __webpack_require__(20416);
;// CONCATENATED MODULE: ./src/.umi-production/plugin-layout/Layout.css
// extracted by mini-css-extract-plugin

// EXTERNAL MODULE: ./node_modules/react/jsx-runtime.js
var jsx_runtime = __webpack_require__(85893);
;// CONCATENATED MODULE: ./src/.umi-production/plugin-layout/Logo.tsx
// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!



var LogoIcon = function LogoIcon() {
  return /*#__PURE__*/(0,jsx_runtime.jsxs)("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    width: "32",
    height: "32",
    viewBox: "0 0 200 200",
    children: [/*#__PURE__*/(0,jsx_runtime.jsxs)("defs", {
      children: [/*#__PURE__*/(0,jsx_runtime.jsxs)("linearGradient", {
        id: "linearGradient-1",
        x1: "62.102%",
        x2: "108.197%",
        y1: "0%",
        y2: "37.864%",
        children: [/*#__PURE__*/(0,jsx_runtime.jsx)("stop", {
          offset: "0%",
          stopColor: "#4285EB"
        }), /*#__PURE__*/(0,jsx_runtime.jsx)("stop", {
          offset: "100%",
          stopColor: "#2EC7FF"
        })]
      }), /*#__PURE__*/(0,jsx_runtime.jsxs)("linearGradient", {
        id: "linearGradient-2",
        x1: "69.644%",
        x2: "54.043%",
        y1: "0%",
        y2: "108.457%",
        children: [/*#__PURE__*/(0,jsx_runtime.jsx)("stop", {
          offset: "0%",
          stopColor: "#29CDFF"
        }), /*#__PURE__*/(0,jsx_runtime.jsx)("stop", {
          offset: "37.86%",
          stopColor: "#148EFF"
        }), /*#__PURE__*/(0,jsx_runtime.jsx)("stop", {
          offset: "100%",
          stopColor: "#0A60FF"
        })]
      }), /*#__PURE__*/(0,jsx_runtime.jsxs)("linearGradient", {
        id: "linearGradient-3",
        x1: "69.691%",
        x2: "16.723%",
        y1: "-12.974%",
        y2: "117.391%",
        children: [/*#__PURE__*/(0,jsx_runtime.jsx)("stop", {
          offset: "0%",
          stopColor: "#FA816E"
        }), /*#__PURE__*/(0,jsx_runtime.jsx)("stop", {
          offset: "41.473%",
          stopColor: "#F74A5C"
        }), /*#__PURE__*/(0,jsx_runtime.jsx)("stop", {
          offset: "100%",
          stopColor: "#F51D2C"
        })]
      }), /*#__PURE__*/(0,jsx_runtime.jsxs)("linearGradient", {
        id: "linearGradient-4",
        x1: "68.128%",
        x2: "30.44%",
        y1: "-35.691%",
        y2: "114.943%",
        children: [/*#__PURE__*/(0,jsx_runtime.jsx)("stop", {
          offset: "0%",
          stopColor: "#FA8E7D"
        }), /*#__PURE__*/(0,jsx_runtime.jsx)("stop", {
          offset: "51.264%",
          stopColor: "#F74A5C"
        }), /*#__PURE__*/(0,jsx_runtime.jsx)("stop", {
          offset: "100%",
          stopColor: "#F51D2C"
        })]
      })]
    }), /*#__PURE__*/(0,jsx_runtime.jsx)("g", {
      fill: "none",
      fillRule: "evenodd",
      stroke: "none",
      strokeWidth: "1",
      children: /*#__PURE__*/(0,jsx_runtime.jsx)("g", {
        transform: "translate(-20 -20)",
        children: /*#__PURE__*/(0,jsx_runtime.jsx)("g", {
          transform: "translate(20 20)",
          children: /*#__PURE__*/(0,jsx_runtime.jsxs)("g", {
            children: [/*#__PURE__*/(0,jsx_runtime.jsxs)("g", {
              fillRule: "nonzero",
              children: [/*#__PURE__*/(0,jsx_runtime.jsxs)("g", {
                children: [/*#__PURE__*/(0,jsx_runtime.jsx)("path", {
                  fill: "url(#linearGradient-1)",
                  d: "M91.588 4.177L4.18 91.513a11.981 11.981 0 000 16.974l87.408 87.336a12.005 12.005 0 0016.989 0l36.648-36.618c4.209-4.205 4.209-11.023 0-15.228-4.208-4.205-11.031-4.205-15.24 0l-27.783 27.76c-1.17 1.169-2.945 1.169-4.114 0l-69.802-69.744c-1.17-1.169-1.17-2.942 0-4.11l69.802-69.745c1.17-1.169 2.944-1.169 4.114 0l27.783 27.76c4.209 4.205 11.032 4.205 15.24 0 4.209-4.205 4.209-11.022 0-15.227L108.581 4.056c-4.719-4.594-12.312-4.557-16.993.12z"
                }), /*#__PURE__*/(0,jsx_runtime.jsx)("path", {
                  fill: "url(#linearGradient-2)",
                  d: "M91.588 4.177L4.18 91.513a11.981 11.981 0 000 16.974l87.408 87.336a12.005 12.005 0 0016.989 0l36.648-36.618c4.209-4.205 4.209-11.023 0-15.228-4.208-4.205-11.031-4.205-15.24 0l-27.783 27.76c-1.17 1.169-2.945 1.169-4.114 0l-69.802-69.744c-1.17-1.169-1.17-2.942 0-4.11l69.802-69.745c2.912-2.51 7.664-7.596 14.642-8.786 5.186-.883 10.855 1.062 17.009 5.837L108.58 4.056c-4.719-4.594-12.312-4.557-16.993.12z"
                })]
              }), /*#__PURE__*/(0,jsx_runtime.jsx)("path", {
                fill: "url(#linearGradient-3)",
                d: "M153.686 135.855c4.208 4.205 11.031 4.205 15.24 0l27.034-27.012c4.7-4.696 4.7-12.28 0-16.974l-27.27-27.15c-4.218-4.2-11.043-4.195-15.254.013-4.209 4.205-4.209 11.022 0 15.227l18.418 18.403c1.17 1.169 1.17 2.943 0 4.111l-18.168 18.154c-4.209 4.205-4.209 11.023 0 15.228z"
              })]
            }), /*#__PURE__*/(0,jsx_runtime.jsx)("ellipse", {
              cx: "100.519",
              cy: "100.437",
              fill: "url(#linearGradient-4)",
              rx: "23.6",
              ry: "23.581"
            })]
          })
        })
      })
    })]
  });
};
/* harmony default export */ var Logo = (LogoIcon);
// EXTERNAL MODULE: ./node_modules/antd/es/result/index.js + 6 modules
var result = __webpack_require__(22181);
// EXTERNAL MODULE: ./node_modules/antd/es/button/index.js + 15 modules
var es_button = __webpack_require__(45093);
;// CONCATENATED MODULE: ./src/.umi-production/plugin-layout/Exception.tsx
// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!




var Exception = function Exception(props) {
  var _props$route, _props$route2;
  return (
    // render custom 404
    !props.route && (props.noFound || props.notFound) ||
    // render custom 403
    ((_props$route = props.route) === null || _props$route === void 0 ? void 0 : _props$route.unaccessible) && (props.unAccessible || props.noAccessible) ||
    // render default exception
    (!props.route || ((_props$route2 = props.route) === null || _props$route2 === void 0 ? void 0 : _props$route2.unaccessible)) && /*#__PURE__*/(0,jsx_runtime.jsx)(result/* default */.ZP, {
      status: props.route ? '403' : '404',
      title: props.route ? '403' : '404',
      subTitle: props.route ? '抱歉，你无权访问该页面' : '抱歉，你访问的页面不存在',
      extra: /*#__PURE__*/(0,jsx_runtime.jsx)(es_button/* default */.ZP, {
        type: "primary",
        onClick: function onClick() {
          return _umi_production_exports.history.push('/');
        },
        children: "\u8FD4\u56DE\u9996\u9875"
      })
    }) ||
    // normal render
    props.children
  );
};
/* harmony default export */ var plugin_layout_Exception = (Exception);
// EXTERNAL MODULE: ./node_modules/antd/es/avatar/index.js + 4 modules
var es_avatar = __webpack_require__(7134);
// EXTERNAL MODULE: ./node_modules/antd/es/spin/index.js + 2 modules
var spin = __webpack_require__(75081);
// EXTERNAL MODULE: ./node_modules/antd/es/version/index.js + 1 modules
var version = __webpack_require__(67159);
// EXTERNAL MODULE: ./node_modules/antd/es/menu/index.js + 11 modules
var menu = __webpack_require__(68508);
// EXTERNAL MODULE: ./node_modules/antd/es/dropdown/index.js + 1 modules
var dropdown = __webpack_require__(85418);
// EXTERNAL MODULE: ./node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/LogoutOutlined.js + 7 modules
var LogoutOutlined = __webpack_require__(57764);
;// CONCATENATED MODULE: ./src/.umi-production/plugin-layout/rightRender.tsx

// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!






function getRightRenderContent(opts) {
  var _opts$initialState, _opts$initialState2, _opts$initialState3, _opts$initialState4, _opts$initialState5;
  if (opts.runtimeConfig.rightRender) {
    return opts.runtimeConfig.rightRender(opts.initialState, opts.setInitialState, opts.runtimeConfig);
  }
  var showAvatar = ((_opts$initialState = opts.initialState) === null || _opts$initialState === void 0 ? void 0 : _opts$initialState.avatar) || ((_opts$initialState2 = opts.initialState) === null || _opts$initialState2 === void 0 ? void 0 : _opts$initialState2.name) || opts.runtimeConfig.logout;
  var disableAvatarImg = ((_opts$initialState3 = opts.initialState) === null || _opts$initialState3 === void 0 ? void 0 : _opts$initialState3.avatar) === false;
  var nameClassName = disableAvatarImg ? 'umi-plugin-layout-name umi-plugin-layout-hide-avatar-img' : 'umi-plugin-layout-name';
  var avatar = showAvatar ? /*#__PURE__*/(0,jsx_runtime.jsxs)("span", {
    className: "umi-plugin-layout-action",
    children: [!disableAvatarImg ? /*#__PURE__*/(0,jsx_runtime.jsx)(es_avatar/* default */.C, {
      size: "small",
      className: "umi-plugin-layout-avatar",
      src: ((_opts$initialState4 = opts.initialState) === null || _opts$initialState4 === void 0 ? void 0 : _opts$initialState4.avatar) || "https://gw.alipayobjects.com/zos/antfincdn/XAosXuNZyF/BiazfanxmamNRoxxVxka.png",
      alt: "avatar"
    }) : null, /*#__PURE__*/(0,jsx_runtime.jsx)("span", {
      className: nameClassName,
      children: (_opts$initialState5 = opts.initialState) === null || _opts$initialState5 === void 0 ? void 0 : _opts$initialState5.name
    })]
  }) : null;
  if (opts.loading) {
    return /*#__PURE__*/(0,jsx_runtime.jsx)("div", {
      className: "umi-plugin-layout-right",
      children: /*#__PURE__*/(0,jsx_runtime.jsx)(spin/* default */.Z, {
        size: "small",
        style: {
          marginLeft: 8,
          marginRight: 8
        }
      })
    });
  }

  // 如果没有打开Locale，并且头像为空就取消掉这个返回的内容
  if (!avatar) return null;
  var langMenu = {
    className: "umi-plugin-layout-menu",
    selectedKeys: [],
    items: [{
      key: "logout",
      label: /*#__PURE__*/(0,jsx_runtime.jsxs)(jsx_runtime.Fragment, {
        children: [/*#__PURE__*/(0,jsx_runtime.jsx)(LogoutOutlined/* default */.Z, {}), "\u9000\u51FA\u767B\u5F55"]
      }),
      onClick: function onClick() {
        var _opts$runtimeConfig, _opts$runtimeConfig$l;
        opts === null || opts === void 0 || (_opts$runtimeConfig = opts.runtimeConfig) === null || _opts$runtimeConfig === void 0 || (_opts$runtimeConfig$l = _opts$runtimeConfig.logout) === null || _opts$runtimeConfig$l === void 0 || _opts$runtimeConfig$l.call(_opts$runtimeConfig, opts.initialState);
      }
    }]
  };
  // antd@5 和  4.24 之后推荐使用 menu，性能更好
  var dropdownProps;
  if (version/* default */.Z.startsWith("5.") || version/* default */.Z.startsWith("4.24.")) {
    dropdownProps = {
      menu: langMenu
    };
  } else if (version/* default */.Z.startsWith("3.")) {
    dropdownProps = {
      overlay: /*#__PURE__*/(0,jsx_runtime.jsx)(menu/* default */.Z, {
        children: langMenu.items.map(function (item) {
          return /*#__PURE__*/(0,jsx_runtime.jsx)(menu/* default */.Z.Item, {
            onClick: item.onClick,
            children: item.label
          }, item.key);
        })
      })
    };
  } else {
    // 需要 antd 4.20.0 以上版本
    dropdownProps = {
      overlay: /*#__PURE__*/(0,jsx_runtime.jsx)(menu/* default */.Z, objectSpread2_default()({}, langMenu))
    };
  }
  return /*#__PURE__*/(0,jsx_runtime.jsx)("div", {
    className: "umi-plugin-layout-right anticon",
    children: opts.runtimeConfig.logout ? /*#__PURE__*/(0,jsx_runtime.jsx)(dropdown/* default */.Z, objectSpread2_default()(objectSpread2_default()({}, dropdownProps), {}, {
      overlayClassName: "umi-plugin-layout-container",
      children: avatar
    })) : avatar
  });
}
// EXTERNAL MODULE: ./src/.umi-production/plugin-model/index.tsx
var plugin_model = __webpack_require__(44886);
// EXTERNAL MODULE: ./src/.umi-production/plugin-access/index.tsx
var plugin_access = __webpack_require__(83228);
;// CONCATENATED MODULE: ./src/.umi-production/plugin-layout/Layout.tsx




// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
/// <reference types="@ant-design/pro-components" />
/// <reference types="antd" />











// 过滤出需要显示的路由, 这里的filterFn 指 不希望显示的层级

var filterRoutes = function filterRoutes(routes, filterFn) {
  if (routes.length === 0) {
    return [];
  }
  var newRoutes = [];
  var _iterator = createForOfIteratorHelper_default()(routes),
    _step;
  try {
    for (_iterator.s(); !(_step = _iterator.n()).done;) {
      var _route = _step.value;
      var newRoute = objectSpread2_default()({}, _route);
      if (filterFn(_route)) {
        if (Array.isArray(newRoute.routes)) {
          newRoutes.push.apply(newRoutes, toConsumableArray_default()(filterRoutes(newRoute.routes, filterFn)));
        }
      } else {
        if (Array.isArray(newRoute.children)) {
          newRoute.children = filterRoutes(newRoute.children, filterFn);
          newRoute.routes = newRoute.children;
        }
        newRoutes.push(newRoute);
      }
    }
  } catch (err) {
    _iterator.e(err);
  } finally {
    _iterator.f();
  }
  return newRoutes;
};

// 格式化路由 处理因 wrapper 导致的 菜单 path 不一致
var mapRoutes = function mapRoutes(routes) {
  if (routes.length === 0) {
    return [];
  }
  return routes.map(function (route) {
    // 需要 copy 一份, 否则会污染原始数据
    var newRoute = objectSpread2_default()({}, route);
    if (route.originPath) {
      newRoute.path = route.originPath;
    }
    if (Array.isArray(route.routes)) {
      newRoute.routes = mapRoutes(route.routes);
    }
    if (Array.isArray(route.children)) {
      newRoute.children = mapRoutes(route.children);
    }
    return newRoute;
  });
};
/* harmony default export */ var Layout = (function (props) {
  var location = (0,_umi_production_exports.useLocation)();
  var navigate = (0,_umi_production_exports.useNavigate)();
  var _useAppData = (0,_umi_production_exports.useAppData)(),
    clientRoutes = _useAppData.clientRoutes,
    pluginManager = _useAppData.pluginManager;
  var initialInfo = plugin_model/* useModel */.t && (0,plugin_model/* useModel */.t)('@@initialState') || {
    initialState: undefined,
    loading: false,
    setInitialState: null
  };
  var initialState = initialInfo.initialState,
    loading = initialInfo.loading,
    setInitialState = initialInfo.setInitialState;
  var userConfig = {
    "title": "智慧景区运营解决方案"
  };
  var formatMessage = undefined;
  var runtimeConfig = pluginManager.applyPlugins({
    key: 'layout',
    type: 'modify',
    initialValue: objectSpread2_default()({}, initialInfo)
  });

  // 现在的 layout 及 wrapper 实现是通过父路由的形式实现的, 会导致路由数据多了冗余层级, proLayout 消费时, 无法正确展示菜单, 这里对冗余数据进行过滤操作
  var newRoutes = filterRoutes(clientRoutes.filter(function (route) {
    return route.id === 'ant-design-pro-layout';
  }), function (route) {
    return !!route.isLayout && route.id !== 'ant-design-pro-layout' || !!route.isWrapper;
  });
  var _useAccessMarkedRoute = (0,plugin_access/* useAccessMarkedRoutes */.Mf)(mapRoutes(newRoutes)),
    _useAccessMarkedRoute2 = slicedToArray_default()(_useAccessMarkedRoute, 1),
    route = _useAccessMarkedRoute2[0];
  var matchedRoute = (0,react.useMemo)(function () {
    var _matchRoutes, _matchRoutes$pop;
    return (_matchRoutes = (0,_umi_production_exports.matchRoutes)(route.children, location.pathname)) === null || _matchRoutes === void 0 || (_matchRoutes$pop = _matchRoutes.pop) === null || _matchRoutes$pop === void 0 || (_matchRoutes$pop = _matchRoutes$pop.call(_matchRoutes)) === null || _matchRoutes$pop === void 0 ? void 0 : _matchRoutes$pop.route;
  }, [location.pathname]);
  return /*#__PURE__*/(0,jsx_runtime.jsx)(ProLayout/* ProLayout */.f, objectSpread2_default()(objectSpread2_default()({
    route: route,
    location: location,
    title: userConfig.title || 'plugin-layout',
    navTheme: "dark",
    siderWidth: 256,
    onMenuHeaderClick: function onMenuHeaderClick(e) {
      e.stopPropagation();
      e.preventDefault();
      navigate('/');
    },
    formatMessage: userConfig.formatMessage || formatMessage,
    menu: {
      locale: userConfig.locale
    },
    logo: Logo,
    menuItemRender: function menuItemRender(menuItemProps, defaultDom) {
      if (menuItemProps.isUrl || menuItemProps.children) {
        return defaultDom;
      }
      if (menuItemProps.path && location.pathname !== menuItemProps.path) {
        return (
          /*#__PURE__*/
          // handle wildcard route path, for example /slave/* from qiankun
          (0,jsx_runtime.jsx)(_umi_production_exports.Link, {
            to: menuItemProps.path.replace('/*', ''),
            target: menuItemProps.target,
            children: defaultDom
          })
        );
      }
      return defaultDom;
    },
    itemRender: function itemRender(route, _, routes) {
      var breadcrumbName = route.breadcrumbName,
        title = route.title,
        path = route.path;
      var label = title || breadcrumbName;
      var last = routes[routes.length - 1];
      if (last) {
        if (last.path === path || last.linkPath === path) {
          return /*#__PURE__*/(0,jsx_runtime.jsx)("span", {
            children: label
          });
        }
      }
      return /*#__PURE__*/(0,jsx_runtime.jsx)(_umi_production_exports.Link, {
        to: path,
        children: label
      });
    },
    disableContentMargin: true,
    fixSiderbar: true,
    fixedHeader: true
  }, runtimeConfig), {}, {
    rightContentRender: runtimeConfig.rightContentRender !== false && function (layoutProps) {
      var dom = getRightRenderContent({
        runtimeConfig: runtimeConfig,
        loading: loading,
        initialState: initialState,
        setInitialState: setInitialState
      });
      if (runtimeConfig.rightContentRender) {
        return runtimeConfig.rightContentRender(layoutProps, dom, {
          // BREAK CHANGE userConfig > runtimeConfig
          userConfig: userConfig,
          runtimeConfig: runtimeConfig,
          loading: loading,
          initialState: initialState,
          setInitialState: setInitialState
        });
      }
      return dom;
    },
    children: /*#__PURE__*/(0,jsx_runtime.jsx)(plugin_layout_Exception, {
      route: matchedRoute,
      noFound: runtimeConfig === null || runtimeConfig === void 0 ? void 0 : runtimeConfig.noFound,
      notFound: runtimeConfig === null || runtimeConfig === void 0 ? void 0 : runtimeConfig.notFound,
      unAccessible: runtimeConfig === null || runtimeConfig === void 0 ? void 0 : runtimeConfig.unAccessible,
      noAccessible: runtimeConfig === null || runtimeConfig === void 0 ? void 0 : runtimeConfig.noAccessible,
      children: runtimeConfig.childrenRender ? runtimeConfig.childrenRender( /*#__PURE__*/(0,jsx_runtime.jsx)(_umi_production_exports.Outlet, {}), props) : /*#__PURE__*/(0,jsx_runtime.jsx)(_umi_production_exports.Outlet, {})
    })
  }));
});

/***/ })

}]);